language: bash
services: docker

env:
  - VERSION=7.2 IMAGES="php fpm"
  - VERSION=7.3 IMAGES="php fpm"
  - VERSION=10 IMAGES="node"
  - VERSION=12 IMAGES="node"

script:
  - ./.ci/build_images.sh
  - ./.ci/run_tests.sh

deploy:
  provider: script
  script: ./.ci/push_images.sh "7.3" "12"
  on:
    branch: master
