name: docker-compose-actions-workflow
on: push
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                VERSION: [ubuntu-latest, macos-latest, windows-latest]
                IMAGES: [ubuntu-latest, macos-latest, windows-latest]
                include:
                    - version: 7.2
                      image: "php fpm"
                    - version: 7.3
                      image: "php fpm"
                    - version: 10
                      image: "node"
                    - version: 12
                      image: "node"
        steps:
            -   uses: actions/checkout@v2
            -   name: Build
                run: ./.ci/build_images.sh
            -   name: Test
                run: ./.ci/run_tests.sh
                env:
                    POSTGRES_HOST: postgres
                    POSTGRES_PORT: 5432
